### ISSUE TITLE
Add methods for getting / adding / editing Data Element on protocols / experiments

### ISSUE THREAD

**Issue by BarneyLabstep** [Labstep/labstepPy#44]
- [x] Method on `Protocol` and `ExperimentProtocol` classes called `getDataElements` which uses the underlying `metadata.getMetadata` function and returns list of class `Metadata`.
- [x] Method on `Protocol` and `ExperimentProtocol` classes called `addDataElement` which uses the underlying `metadata.addMetadataTo` function.

**Comment by jandom** [comment]
@BarneyLabstep from my understanding there is no Metadata associated with ExperimentProtocol ('experiment'); instead it's available to ExperimentWorkflows?

**Comment by BarneyLabstep** [comment]
Ah yes, it's both actually.

**Comment by jandom** [comment]
Another question: why `addDataElement` if the Resource class uses `addMetadata`? Shouldn't we keep things harmonized?

**Comment by jandom** [comment]
Looks like the PR is merged – done
