### ISSUE TITLE
Set up CI/CD

### ISSUE THREAD

**Issue by BarneyLabstep** [Labstep/labstepPy#47]
- Package should auto-publish to PyPi from the master branch
- Package should auto-publish to test-PyPi from the develop branch

**Comment by jandom** [comment]
This is an interesting one, so it's really about the CD part - or CP, continuous publishing. 

The CI part is already setup, from what I can see, on circleCi.

**Comment by jandom** [comment]
Starting the thread with PyPI publication https://github.com/Labstep/labstepPy/pull/48

**Comment by jandom** [comment]
This is done and working now, closing
