### ISSUE TITLE
getMaterials and addMaterial methods on Experiments

### ISSUE THREAD

**Issue by BarneyLabstep** [Labstep/labstepPy#50]
- Materials can now be added directly to experiments on the web-app.

We should add methods to allow this via the SDK.

**Comment by jandom** [comment]
I think I've already added this as part of the other PR?

**Comment by BarneyLabstep** [comment]
Which PR? I don't see it in the Data elements one. For clarity here I am talking about Experiments using the naming convention of the SDK and the web app (experiment_workflows on the backend).

**Comment by BarneyLabstep** [comment]
Shipped.
